// Generated by CoffeeScript 1.4.0
(function() {
  var Flat;

  Flat = (function() {

    function Flat() {
      this.$flat = $('[flat]');
      this.$views = $('[view]');
      this.$views.not(':first').hide();
      this.attachEvents();
    }

    Flat.prototype.attachEvents = function() {
      var self;
      self = this;
      return $('[trigger]').on('click', function(e) {
        var el, view;
        el = $(this);
        view = el.attr('trigger');
        return self.view(view);
      });
    };

    Flat.prototype.updateColor = function(color) {
      color = color || this.$flat.attr('wireframer');
      return this.$flat.find('*').css({
        'borderColor': color
      });
    };

    Flat.prototype.view = function(view) {
      this.currentView = this.$views.filter(':visible');
      this.currentView.hide();
      return $('[view="' + view + '"]').show();
    };

    return Flat;

  })();

  $(function() {
    var possibleColors, wireframer;
    wireframer = new WireFramer();
    possibleColors = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 'a', 'b', 'c', 'd', 'e', 'f'];
    return window.setInterval(function() {
      var color, i, _i;
      color = '';
      for (i = _i = 0; _i < 6; i = ++_i) {
        color += possibleColors[Math.floor(Math.random() * possibleColors.length)];
      }
      console.log(color);
      return wireframer.updateColor('#' + color);
    }, 2000);
  });

}).call(this);
